model:
    backend: "transformers"
    model_name: "meta-llama/Llama-3.2-3B-Instruct"
    task_type: "causal"
    language: "en"
    device: "mps"
    cp_dir: ".models/llama-3.2-3B-Instruct-mediasum"

limits:
    max_input_length: 512
    max_output_tokens: 1024
